### PR TITLE
Python3 port

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
i have created a new branch "python3" for it, maybe you want to do the same.

if you can easily do practical testing, please give feedback.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
as an additional note: the "port" uses same sourcecode for py2 and py3 (not 2to3), it is same method as we used for flask porting and reuses _compat code from there.

**Comment by thadeusb** [comment]
Once Flask 0.10 is released we can merge this into master.

**Comment by thadeusb** [comment]
I went ahead and pulled it into branch ThomasWaldmann-python3 to continue any work necessary.

**Comment by 1xch** [comment]
I'm trying to use this with flask-0.10 & python 3.3

```
pip install git+git://github.com/thadeusb/flask-cache.git@ThomasWaldmann-python3
```

Installs fine, however the first error I have to report:

```
File "/.virtualenvs/j3/lib/python3.3/site-packages/flask_cache/__init__.py", line 106, in init_app self._set_cache(app, config)
File "/.virtualenvs/j3/lib/python3.3/site-packages/flask_cache/__init__.py", line 111, in _set_cache from . import backends
File "/.virtualenvs/j3/lib/python3.3/site-packages/flask_cache/backends.py", line 4, in <module> from flask._compat import range_type
ImportError: cannot import name range_type
```

**Comment by untitaker** [comment]
@ThomasWaldmann Depending on flask._compat will make this extension depend on Flask >= 0.10, even though it could work with earlier versions in Python 2.

**Comment by ThomasWaldmann** [comment]
Yup, will fix it by having a local private _compat.py in flask_cache.

**Comment by untitaker** [comment]
Any updates on this?

**Comment by ThomasWaldmann** [comment]
Any updates on this?

**Pull request merged**
