### PR TITLE
Adds per-instance cache versioning for memoize()

### PR DESCRIPTION
**Pull request by bslatkin**
Adds the 'per_instance' keyword to memoize().

If set to True, the cache key versioning used will be scoped to the function's first argument (i.e., a method's bound object). This lets you cache many different calls to one memoized function for a single object (like a user) and later clear all data cached for that object with a single call to delete_memoized.

Importantly: This is achieved with no additional round-trips to the cache for the per-method version. The code uses the get_many/set_many functions so the only difference is the number of keys get/set.

Various other clean-up including:
- Unify version setting code in _memoize_version
- Make _memoize_kwargs_to_args protected
- Only one call-site for function_namespace, making it easier to follow
- Updated docs with notes about per_method usage
- Updates the SpreadSASLMemcachedCache backend to handle set_many/get_many/delete_many
- Alphabetize import statements
- Cleans a few docstrings

Let me know what I need to do to land this! Thanks.

### CODE REVIEW

**Comment by bslatkin** [comment]
Okay @thadeusb I think this is ready for review. All tests are passing locally for me with TRAVIS=1, so I actually test against Redis and Memcached. The Travis CI build was half successful. My guess is there's flakiness in the tests there for some reason. I'm running this code in production at http://dpxdt-test.appspot.com.

Please let me know what I can do to get this landed. Thanks!

**Comment by thadeusb** [comment]
There is quite a bit here, I need to contemplate some of these changes a bit more.

**Comment by thadeusb** [comment]
It appears that the main feature of this pull request is to add support to delete the memoized cache across all instances of a class. Caching on a per-instance is already supported by overriding the **repr** function of the class and specifying some uniquely identifying information (such as user id), and also having the id or hex of the class returned as well could keep every instance of the class separate. 

Since unbound methods are removed in python 3, there needs to be another way to perform delete_memoize, as there is no way to determine the class of a function that is not bound to a object.

**Comment by bslatkin** [comment]
@thadeusb Thanks for the review.

You said this:

```
It appears that the main feature of this pull request is to add support
to delete the memoized cache across all instances of a class.
```

Not quite. Sorry I didn't explain better.

What this change lets you do is delete the memoization cache for all sets of parameters to one memoized method belonging to a single instance.

Right now with flask_cache if you call `my_object.my_method.delete_memoized()` that will delete the cache for all versions of that function across all instances with all parameters.

What I want instead is this only deletes the cache for just `my_object.my_method` and all parameters. Another object with the same method would be left alone: `my_other_object.my_method`. The same object but a different method would be left alone `my_object.my_other_method`. But all variations of parameters for `my_object.my_method` would be cleared. It identifies `my_object` using `__repr__` exactly as you describe.

Does that make sense?

**Comment by bslatkin** [comment]
Poke. Any thoughts here?

**Comment by bslatkin** [comment]
Okay I'm throwing this away.

**Pull request closed without merging**
