### PR TITLE
fix the #177

### PR DESCRIPTION
**Pull request by ponytailer**
fix the #177 : when the function has the magic arguments, the make_memorize_cache_key has the bug.

### CODE REVIEW

**Comment by ponytailer** [comment]
The CI has been down.

**Comment by dengshaochun** [comment]
#174 
error msg
```
$ python --version
Python 2.7.13
$ pip --version
pip 9.0.1 from /home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages (python 2.7)
0.28s$ pip install . --use-mirrors
Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...
no such option: --use-mirrors
The command "pip install . --use-mirrors" failed and exited with 2 during .
```

**Comment by ponytailer** [comment]
Got it, thanks

**Comment by ponytailer** [comment]
But, maybe the author has not accepted the new PR.

**Comment by ponytailer** [comment]
Now, `memorize` support the magic arguments, so remove and fixed those test case.

**Pull request closed without merging**
