### PR TITLE
Support multi app and multi cache (fix #53)

### LINKED ISSUE #53: Can't have more then 1 instance of Cache() in latest versions
because `_set_cache` sets `app.extensions['cache']` and uses that for accessing the cache too it's not possible to have multiple instances of Cache() (eg. one local in-memory cache, one redis cache, one memcache cache).

in v0.8.0 this was still possible ...

### PR DESCRIPTION
**Pull request by methane**
Support multi app and multi cache (fix #53)

### CODE REVIEW

**Comment by untitaker** [comment]
Did you actually test this? In order for this to work, Cache objects need to be hashable, which is, IIRC, not the case.

**Comment by methane** [comment]
Python's user defined class is hashable by default.

http://docs.python.org/2/reference/datamodel.html#object.__hash__

> User-defined classes have **cmp**() and **hash**() methods by default; with them, all objects compare unequal (except with themselves) and x.**hash**() returns id(x).

**Comment by untitaker** [comment]
Huh, TIL.

**Comment by thadeusb** [comment]
commit 31e0d3a648a1ebf3a83c7cd90fd606483308f0f3

**Pull request merged**
